path_classifiers:
   external:
      - dependencies
      - "include/diplib/private/pcg_*.hpp"
      - tools
   test:
      - exclude: /
      - examples/pydip_examples.py
queries:
   - exclude: cpp/large-parameter
extraction:
   cpp:
      prepare:
         packages:
            - freeglut3-dev
            - python3-dev
      after_prepare:
         - export GNU_MAKE=make
         - export GIT=true
         - mkdir $LGTM_SRC/target
      configure:
         command:
            - cd $LGTM_SRC/target && cmake ..
      index:
         build_command:
            - cd $LGTM_SRC/target && $GNU_MAKE -j2
