language: cpp
os: linux
dist: xenial
compiler:
  - clang
  - gcc
addons:
   apt:
      packages:
         - freeglut3-dev
         - libglfw3-dev
         - python3-dev
script:
  - mkdir build
  - cd build
  - export DIP_CMAKE_OPTS=$(if [[ $CC == "clang" ]]; then echo -n '-DDIP_ENABLE_MULTITHREADING=Off'; fi)
  - cmake ..
  - make -j2
  - make check
