language: cpp
matrix:
  include:
     - os: linux
       dist: xenial
       compiler: clang
     - os: linux
       dist: xenial
       compiler: gcc
     - os: osx
       osx_image: xcode10.2
       compiler: clang
     - os: windows
addons:
  apt:
    packages:
      - freeglut3-dev
      - libglfw3-dev
      - python3-dev
  homebrew:
    packages:
      - freeglut
      - glfw
      - python
branches:
  except:
    - cris

script:
  - mkdir build
  - cd build
  - export DIP_CMAKE_OPTS=$(if [[ $CC == "clang" ]]; then echo -n '-DDIP_ENABLE_MULTITHREADING=Off'; fi)
  - cmake $DIP_CMAKE_OPTS ..
  - cmake --build . --parallel 2
  - cmake --build . --target check
