language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      env: DIP_CMAKE_OPTS="-DDIP_ENABLE_MULTITHREADING=Off -DPYBIND11_PYTHON_VERSION=3.5"
    - os: linux
      dist: xenial
      compiler: gcc
      env: DIP_CMAKE_OPTS="-DPYBIND11_PYTHON_VERSION=3.5"
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: DIP_CMAKE_OPTS="-DDIP_ENABLE_MULTITHREADING=Off"
      before_install:
        - brew install glfw
    - os: windows
      env: DIP_CMAKE_OPTS="-A x64"
      before_install:
        - choco install python3
        # https://travis-ci.community/t/windows-builds-refreshenv-command-not-found/5803/4
        - eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')
addons:
  apt:
    packages:
      - freeglut3-dev
      - python3-dev
      - python3-pip
branches:
  except:
    - cris

script:
  - pip3 install numpy wheel setuptools
  - mkdir build
  - cd build
  - cmake $DIP_CMAKE_OPTS -DDIP_ENABLE_ASSERT=ON -DDIP_PYDIP_WHEEL_INCLUDE_LIBS=ON ..
  - cmake --build . --parallel 2
  - cmake --build . --target check
  - cmake --build . --target bdist_wheel
