# Automatically generated, don't edit!
set(DIPimage_sources_bogus
dipimage/@dip_image/all.cpp
dipimage/@dip_image/any.cpp
dipimage/@dip_image/circshift.cpp
dipimage/@dip_image/cross.cpp
dipimage/@dip_image/cumsum.cpp
dipimage/@dip_image/curl.cpp
dipimage/@dip_image/det.cpp
dipimage/@dip_image/divergence.cpp
dipimage/@dip_image/dot.cpp
dipimage/@dip_image/eig.cpp
dipimage/@dip_image/gradient.cpp
dipimage/@dip_image/inv.cpp
dipimage/@dip_image/max.cpp
dipimage/@dip_image/mean.cpp
dipimage/@dip_image/min.cpp
dipimage/@dip_image/norm.cpp
dipimage/@dip_image/percentile.cpp
dipimage/@dip_image/pinv.cpp
dipimage/@dip_image/private/colorspacemanager.cpp
dipimage/@dip_image/private/dip_operators.cpp
dipimage/@dip_image/private/dip_tensor_indices.cpp
dipimage/@dip_image/prod.cpp
dipimage/@dip_image/std.cpp
dipimage/@dip_image/sum.cpp
dipimage/@dip_image/svd.cpp
dipimage/@dip_image/trace.cpp
dipimage/@dip_image/var.cpp
dipimage/areaopening.cpp
dipimage/asf.cpp
dipimage/bclosing.cpp
dipimage/bdilation.cpp
dipimage/berosion.cpp
dipimage/bopening.cpp
dipimage/bpropagation.cpp
dipimage/bskeleton.cpp
dipimage/canny.cpp
dipimage/ced.cpp
dipimage/clip.cpp
dipimage/closing.cpp
dipimage/convolve.cpp
dipimage/coordinates.cpp
dipimage/countneighbors.cpp
dipimage/derivative.cpp
dipimage/dilation.cpp
dipimage/drawline.cpp
dipimage/drawpolygon.cpp
dipimage/drawshape.cpp
dipimage/dt.cpp
dipimage/entropy.cpp
dipimage/erfclip.cpp
dipimage/erosion.cpp
dipimage/errormeasure.cpp
dipimage/extendregion.cpp
dipimage/findmaxima.cpp
dipimage/findminima.cpp
dipimage/findshift.cpp
dipimage/ft.cpp
dipimage/gaussianblob.cpp
dipimage/gaussianedgeclip.cpp
dipimage/gaussianlineclip.cpp
dipimage/gdt.cpp
dipimage/get_subpixel.cpp
dipimage/getmaximumandminimum.cpp
dipimage/getsamplestatistics.cpp
dipimage/gradmag.cpp
dipimage/hessian.cpp
dipimage/hist_equalize.cpp
dipimage/hitmiss.cpp
dipimage/hmaxima.cpp
dipimage/hminima.cpp
dipimage/kuwahara.cpp
dipimage/label.cpp
dipimage/laplace.cpp
dipimage/lee.cpp
dipimage/lut.cpp
dipimage/maxima.cpp
dipimage/mdhistogram.cpp
dipimage/measure.cpp
dipimage/minima.cpp
dipimage/noise.cpp
dipimage/noisestd.cpp
dipimage/nonmaximumsuppression.cpp
dipimage/opening.cpp
dipimage/overlay.cpp
dipimage/pathopening.cpp
dipimage/percf.cpp
dipimage/pmd.cpp
dipimage/private/imagedisplay.cpp
dipimage/private/libraryinformation.cpp
dipimage/private/numberofthreads.cpp
dipimage/private/readtiffseries.cpp
dipimage/radialmax.cpp
dipimage/radialmean.cpp
dipimage/radialmin.cpp
dipimage/radialsum.cpp
dipimage/rankmax_opening.cpp
dipimage/rankmin_closing.cpp
dipimage/readics.cpp
dipimage/readtiff.cpp
dipimage/reconstruction.cpp
dipimage/relabel.cpp
dipimage/resample.cpp
dipimage/rotation.cpp
dipimage/select.cpp
dipimage/selectionf.cpp
dipimage/setborder.cpp
dipimage/skew.cpp
dipimage/smallobjectsremove.cpp
dipimage/stretch.cpp
dipimage/structuretensor.cpp
dipimage/subpixlocation.cpp
dipimage/threshold.cpp
dipimage/tophat.cpp
dipimage/unif.cpp
dipimage/varif.cpp
dipimage/vdt.cpp
dipimage/waterseed.cpp
dipimage/watershed.cpp
dipimage/writeics.cpp
dipimage/writetiff.cpp
)
