# Automatically generated, don't edit!
set(DIPlib_sources_bogus
include/dip_matlab_interface.h
include/dip_mmorph_interface.h
include/diplib.h
include/diplib/analysis.h
include/diplib/binary.h
include/diplib/boundary.h
include/diplib/chain_code.h
include/diplib/color.h
include/diplib/dft.h
include/diplib/display.h
include/diplib/distance.h
include/diplib/file_io.h
include/diplib/framework.h
include/diplib/generation.h
include/diplib/generic_iterators.h
include/diplib/geometry.h
include/diplib/histogram.h
include/diplib/iterators.h
include/diplib/kernel.h
include/diplib/library/clamp_cast.h
include/diplib/library/copy_buffer.h
include/diplib/library/datatype.h
include/diplib/library/dimension_array.h
include/diplib/library/error.h
include/diplib/library/image.h
include/diplib/library/image_views.h
include/diplib/library/numeric.h
include/diplib/library/operators.h
include/diplib/library/physical_dimensions.h
include/diplib/library/sample_iterator.h
include/diplib/library/tensor.h
include/diplib/library/types.h
include/diplib/linear.h
include/diplib/lookup_table.h
include/diplib/mapping.h
include/diplib/math.h
include/diplib/measurement.h
include/diplib/microscopy.h
include/diplib/morphology.h
include/diplib/multithreading.h
include/diplib/neighborlist.h
include/diplib/nonlinear.h
include/diplib/overload.h
include/diplib/pixel_table.h
include/diplib/private/monadic_operators.h
include/diplib/random.h
include/diplib/regions.h
include/diplib/saturated_arithmetic.h
include/diplib/segmentation.h
include/diplib/statistics.h
include/diplib/testing.h
include/diplib/transform.h
include/diplib/union_find.h
src/analysis/findshift.cpp
src/analysis/fractal_dimension.cpp
src/analysis/structure_tensor.cpp
src/analysis/subpixel_location.cpp
src/binary/bucket.h
src/binary/count_neighbors.cpp
src/binary/skeleton.cpp
src/color/cmyk.h
src/color/color.cpp
src/color/hcv.h
src/color/hsi.h
src/color/ish.h
src/color/lab.h
src/color/rgb.h
src/color/xyz.h
src/display/colormap.cpp
src/display/image_display.cpp
src/distance/edt.cpp
src/distance/gdt.cpp
src/distance/vdt.cpp
src/file_io/ics.cpp
src/file_io/tiff_read.cpp
src/file_io/tiff_write.cpp
src/generation/coordinates.cpp
src/generation/noise.cpp
src/geometry/interpolation.h
src/geometry/resampling.cpp
src/histogram/histogram.cpp
src/histogram/statistics.cpp
src/histogram/threshold_algorithms.cpp
src/library/boundary.cpp
src/library/copy_buffer.cpp
src/library/datatype.cpp
src/library/framework.cpp
src/library/framework_full.cpp
src/library/framework_scan.cpp
src/library/framework_separable.cpp
src/library/image.cpp
src/library/image_copy.cpp
src/library/image_data.cpp
src/library/image_indexing.cpp
src/library/image_manip.cpp
src/library/image_views.cpp
src/library/multithreading.cpp
src/library/neighborhood.cpp
src/library/physical_dimensions.cpp
src/library/pixel_table.cpp
src/library/unit_tests.cpp
src/library/unit_tests_shared_lib.cpp
src/linear/convolution.cpp
src/linear/derivative.cpp
src/linear/finitediff.cpp
src/linear/gauss.cpp
src/linear/gaussiir.cpp
src/linear/separate_filter.cpp
src/linear/sharpen.cpp
src/linear/uniform.cpp
src/mapping/lookup_table.cpp
src/mapping/mapping.cpp
src/math/arithmetic.cpp
src/math/bitwise.cpp
src/math/comparison.cpp
src/math/dyadic_operators.cpp
src/math/error.cpp
src/math/monadic_operators.cpp
src/math/pixel.cpp
src/math/projection.cpp
src/math/select.cpp
src/math/statistics.cpp
src/math/tensor_operators.cpp
src/measurement/convex_hull.cpp
src/measurement/feature_aspect_ratio_feret.h
src/measurement/feature_bending_energy.h
src/measurement/feature_cartesian_box.h
src/measurement/feature_center.h
src/measurement/feature_convex_area.h
src/measurement/feature_convex_perimeter.h
src/measurement/feature_convexity.h
src/measurement/feature_dimensions_cube.h
src/measurement/feature_dimensions_ellipsoid.h
src/measurement/feature_directional_statistics.h
src/measurement/feature_ellipse_variance.h
src/measurement/feature_feret.h
src/measurement/feature_gravity.h
src/measurement/feature_grey_dimensions_cube.h
src/measurement/feature_grey_dimensions_ellipsoid.h
src/measurement/feature_grey_inertia.h
src/measurement/feature_grey_major_axes.h
src/measurement/feature_grey_mu.h
src/measurement/feature_inertia.h
src/measurement/feature_major_axes.h
src/measurement/feature_mass.h
src/measurement/feature_max_val.h
src/measurement/feature_maximum.h
src/measurement/feature_mean.h
src/measurement/feature_min_val.h
src/measurement/feature_minimum.h
src/measurement/feature_mu.h
src/measurement/feature_p2a.h
src/measurement/feature_perimeter.h
src/measurement/feature_podczeck_shapes.h
src/measurement/feature_radius.h
src/measurement/feature_size.h
src/measurement/feature_statistics.h
src/measurement/feature_stdandard_deviation.h
src/measurement/feature_surface_area.cpp
src/measurement/feature_surface_area.h
src/measurement/image_chain_code.cpp
src/measurement/measure_chain_code.cpp
src/measurement/measure_convex_hull.cpp
src/measurement/measurement.cpp
src/measurement/measurement_tool.cpp
src/measurement/object_to_measurement.cpp
src/morphology/areaopening.cpp
src/morphology/basic.cpp
src/morphology/filters.cpp
src/morphology/maxima.cpp
src/morphology/pathopening.cpp
src/morphology/reconstruction.cpp
src/morphology/watershed.cpp
src/morphology/watershed_support.cpp
src/morphology/watershed_support.h
src/nonlinear/kuwahara.cpp
src/nonlinear/percentile.cpp
src/nonlinear/variancefilter.cpp
src/regions/label.cpp
src/regions/label_manipulation.cpp
src/regions/labelingGrana2016.h
src/segmentation/threshold.cpp
src/support/math_functions.cpp
src/support/matrix.cpp
src/transform/fourier.cpp
src/transform/opencv_dxt.cpp
)
