# Automatically generated, don't edit!
set(DIPviewer_sources_bogus
viewer/include/diplib/viewer/control.h
viewer/include/diplib/viewer/glfw.h
viewer/include/diplib/viewer/glut.h
viewer/include/diplib/viewer/histogram.h
viewer/include/diplib/viewer/image.h
viewer/include/diplib/viewer/include_gl.h
viewer/include/diplib/viewer/manager.h
viewer/include/diplib/viewer/slice.h
viewer/include/diplib/viewer/tensor.h
viewer/include/diplib/viewer/viewer.h
viewer/include/dipviewer.h
viewer/src/colormap.cpp
viewer/src/control.cpp
viewer/src/dipviewer.cpp
viewer/src/histogram.cpp
viewer/src/image.cpp
viewer/src/manager.cpp
viewer/src/manager/fg_font_data.h
viewer/src/manager/glfw.cpp
viewer/src/manager/glut.cpp
viewer/src/slice.cpp
viewer/src/tensor.cpp
)
