# Automatically generated, don't edit!
set(PyDIP_sources_bogus
src/PyDIP_py.py
src/__init__.py.in
src/__main__.py
src/analysis.cpp
src/assorted.cpp
src/dipview.py
src/documentation_strings.h
src/documentation_urls.py
src/filtering.cpp
src/generation.cpp
src/histogram.cpp
src/image.cpp
src/javaio.py
src/loadjvm.py
src/math.cpp
src/measurement.cpp
src/morphology.cpp
src/pydip.cpp
src/pydip.h
src/segmentation.cpp
src/statistics.cpp
src/viewer.py
)
