# Automatically generated, don't edit!
set(DIPviewer_sources_bogus
../include/diplib/viewer/control.h
../include/diplib/viewer/export.h
../include/diplib/viewer/glfw.h
../include/diplib/viewer/glut.h
../include/diplib/viewer/histogram.h
../include/diplib/viewer/image.h
../include/diplib/viewer/include_gl.h
../include/diplib/viewer/link.h
../include/diplib/viewer/manager.h
../include/diplib/viewer/proxy.h
../include/diplib/viewer/slice.h
../include/diplib/viewer/status.h
../include/diplib/viewer/tensor.h
../include/diplib/viewer/viewer.h
../include/dipviewer.h
src/colormap.cpp
src/control.cpp
src/dipviewer.cpp
src/fg_font_data.h
src/histogram.cpp
src/image.cpp
src/link.cpp
src/manager.cpp
src/manager/glfw.cpp
src/manager/glut.cpp
src/manager/proxy.cpp
src/slice.cpp
src/status.cpp
src/tensor.cpp
)
