# Automatically generated, don't edit!
set(DIPimage_sources_bogus
@dip_image/eig.cpp
@dip_image/private/colorspacemanager.cpp
@dip_image/private/dip_operators.cpp
@dip_image/private/dip_projection.cpp
@dip_image/private/dip_tensor_indices.cpp
@dip_image/svd.cpp
affine_trans.cpp
canny.cpp
chordlength.cpp
clip.cpp
cluster.cpp
coordinates.cpp
cornerdetector.cpp
distancedistribution.cpp
drawline.cpp
drawpolygon.cpp
drawshape.cpp
dt.cpp
entropy.cpp
erfclip.cpp
errormeasure.cpp
extendregion.cpp
findmaxima.cpp
findminima.cpp
findshift.cpp
fmmatch.cpp
gaussianblob.cpp
gaussianedgeclip.cpp
gaussianlineclip.cpp
gdt.cpp
get_subpixel.cpp
getmaximumandminimum.cpp
getsamplestatistics.cpp
granulometry.cpp
hist_equalize.cpp
integral_image.cpp
label.cpp
linedetector.cpp
lut.cpp
mdhistogram.cpp
mdhistogrammap.cpp
measure.cpp
monogenicsignal.cpp
noise.cpp
noisestd.cpp
nonmaximumsuppression.cpp
overlay.cpp
paircorrelation.cpp
perobjecthist.cpp
private/dip_fileio.cpp
private/dip_filtering.cpp
private/dip_morphology.cpp
private/imagedisplay.cpp
private/libraryinformation.cpp
private/numberofthreads.cpp
psf.cpp
radialmax.cpp
radialmean.cpp
radialmin.cpp
radialsum.cpp
resample.cpp
rotation.cpp
select.cpp
semivariogram.cpp
setborder.cpp
skew.cpp
smallobjectsremove.cpp
stretch.cpp
structuretensor.cpp
subpixlocation.cpp
testobject.cpp
threshold.cpp
traceobjects.cpp
vdt.cpp
wrap.cpp
)
