# Automatically generated, don't edit!
set(DIPimage_sources_bogus
@dip_image/eig.cpp
@dip_image/private/colorspacemanager.cpp
@dip_image/private/dip_operators.cpp
@dip_image/private/dip_tensor_indices.cpp
    @dip_image/private/dip_projection.cpp
@dip_image/svd.cpp
affine_trans.cpp
areaopening.cpp
asf.cpp
bclosing.cpp
bdilation.cpp
berosion.cpp
bopening.cpp
bpropagation.cpp
bskeleton.cpp
canny.cpp
chordlength.cpp
clip.cpp
closing.cpp
cluster.cpp
coordinates.cpp
cornerdetector.cpp
countneighbors.cpp
dilation.cpp
distancedistribution.cpp
drawline.cpp
drawpolygon.cpp
drawshape.cpp
dt.cpp
entropy.cpp
erfclip.cpp
erosion.cpp
errormeasure.cpp
extendregion.cpp
findmaxima.cpp
findminima.cpp
findshift.cpp
fmmatch.cpp
gaussianblob.cpp
gaussianedgeclip.cpp
gaussianlineclip.cpp
gdt.cpp
get_subpixel.cpp
getmaximumandminimum.cpp
getsamplestatistics.cpp
granulometry.cpp
hist_equalize.cpp
hitmiss.cpp
hmaxima.cpp
hminima.cpp
integral_image.cpp
label.cpp
lee.cpp
linedetector.cpp
lut.cpp
maxima.cpp
mdhistogram.cpp
mdhistogrammap.cpp
measure.cpp
minima.cpp
monogenicsignal.cpp
noise.cpp
noisestd.cpp
nonmaximumsuppression.cpp
opening.cpp
overlay.cpp
paircorrelation.cpp
pathopening.cpp
perobjecthist.cpp
private/dip_filtering.cpp
private/imagedisplay.cpp
private/libraryinformation.cpp
private/numberofthreads.cpp
private/readtiffseries.cpp
psf.cpp
radialmax.cpp
radialmean.cpp
radialmin.cpp
radialsum.cpp
rankmax_opening.cpp
rankmin_closing.cpp
readics.cpp
readtiff.cpp
reconstruction.cpp
resample.cpp
rotation.cpp
select.cpp
semivariogram.cpp
setborder.cpp
skew.cpp
smallobjectsremove.cpp
stretch.cpp
structuretensor.cpp
subpixlocation.cpp
testobject.cpp
threshold.cpp
tophat.cpp
traceobjects.cpp
vdt.cpp
waterseed.cpp
watershed.cpp
wrap.cpp
writeics.cpp
writetiff.cpp
)
