# Automatically generated, don't edit!
set(DIPimage_sources_bogus
@dip_image/eig.cpp
@dip_image/private/colorspacemanager.cpp
@dip_image/private/dip_operators.cpp
@dip_image/private/dip_projection.cpp
@dip_image/private/dip_tensor_indices.cpp
@dip_image/svd.cpp
measure.cpp
private/dip_analysis.cpp
private/dip_fileio.cpp
private/dip_filtering.cpp
private/dip_generation.cpp
private/dip_geometry.cpp
private/dip_math.cpp
private/dip_morphology.cpp
private/dip_segmentation.cpp
private/imagedisplay.cpp
private/libraryinformation.cpp
private/numberofthreads.cpp
)
