name: CT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name:  Install
      run:   |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  apt install freeglut3-dev python3-dev python3-pip
                  python3 -m pip install setuptools numpy wheel twine==1.15.0
             elif [ "$RUNNER_OS" == "Windows" ]; then
                  choco install openjdk8
                  choco install python3
                  python -m pip install wheel setuptools numpy twine==1.15.0 wget
             elif [ "$RUNNER_OS" == "macOS" ]; then
                  brew install libomp glfw
                  python3 -m pip install setuptools numpy wheel twine==1.15.0 delocate
             fi
      shell: bash
  
    - name: Configure
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDIP_ENABLE_ASSERT=ON -DDIP_PYDIP_WHEEL_INCLUDE_LIBS=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      # Execute tests defined by the CMake configuration.  
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check

    - name: Package
      # Create the Python distribution wheel
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target bdist_wheel
