name: deploy

on: workflow_dispatch

jobs:
  deploy_macos_x86_64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        # Install libraries and Python packages we need
        # Note that twine and delocate and so on are installed by deploy_macos.sh
        # If Homebrew doesn't know the newest Python version or something like that, add:
        #     export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        #     brew update
        run: |
          brew install libomp glfw wget

      - name: Deploy
        run: bash tools/build/deploy_macos.sh
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          HOMEBREW_DIR: /usr/local
          BUILD_THREADS: 3
          MACOSX_DEPLOYMENT_TARGET: 12.0

  deploy_macos_aarch64:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Install
        # Install libraries and Python packages we need
        # Note that twine and delocate and so on are installed by deploy_macos.sh
        # If Homebrew doesn't know the newest Python version or something like that, add:
        #     export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        #     brew update
        run: |
          brew install libomp glfw wget

      - name: Deploy
        run: bash tools/build/deploy_macos.sh
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          HOMEBREW_DIR: /opt/homebrew
          BUILD_THREADS: 3
          MACOSX_DEPLOYMENT_TARGET: 12.0
