name: deploy

on: workflow_dispatch

jobs:
  deploy_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        # Install libraries and Python packages we need
        run: python3 -m pip install -U twine

      - name: Deploy
        run: bash tools/build/deploy_linux.sh
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
