name: deploy

on: workflow_dispatch

jobs:
  deploy_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        # Install libraries and Python packages we need
        # Note that twine and delocate and so on are installed by deploy_macos.sh
        run: |
          brew install libomp glfw
          python3 -m pip install numpy

      - name: Deploy
        run: bash tools/travis/deploy_macos.sh
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
