name: deploy

on: workflow_dispatch

jobs:

  deploy_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install
        # Install libraries and Python packages we need
        run: |
          choco install openjdk8 --no-progress --yes
          python -m pip install wheel build twine wget

      - name: Deploy
        run: tools/build/deploy_windows.bat
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
